### ISSUE TITLE
Default user issue

### ISSUE THREAD

**Issue by callFEELD** [HuiiBuh/spotify-playlist-colloboration#39]
On an upgrade/update, the default user will be added again to the database.
However, if there are already users in the database (due to the docker volume), this is not necessary.
Not setting the variables in the `.env` file results in an empty user entry (username: "", password: "")

How about adding the default user on the flask side. This can check if users are already defined and cancel the creation of a default user.

**Comment by HuiiBuh** [comment]
There is no problem there as the default user will not be added if the script detects that the username of the default user already exists

**Comment by callFEELD** [comment]
ok that is great
